---
- hosts: "*"
  become: yes
  become_method: sudo
  tasks: 
  - name: "create a user"
    user: name="{{ item.name }}"
    with_items: "{{users}}"
  - name: "add ssh key"
    authorized_key: user="{{ item.name }}" key="{{ item.key }}"
    with_items: "{{users}}"
  vars:
    users:
    - name: george
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCm57cXosJc6O7myfScUNOa7FBoKk02/He8bnnZsv9FvEb8IviTzhmHFt9iU5rTqXfM8OWc7OaYkKKUO83naGiJD4rTtOnV6/syE83cmOYy6jVhAWeYCcNHUyHfhad3h1i66U6WjEbjuM/8h9iLns1XuS0juCNSCrJLLyRz+GP5MIVsz01bqM1yGYbbzKkq2R0p/KTFFiCOdFGrxZpT/TNLROas5F0y6uuBY94STCk00ycHSQ1DF/dgQo3FIvEnNmvebLx3Ox4AMLjHVump5aWIeCJ9eNSFRbnsTDvhzULHprecxH0ifi6xu9WEf1goIkINAUWrOVQ7CkhWu5VShLll robotarmy@Ryans-MBP.lan"
    - name: jorge
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCm57cXosJc6O7myfScUNOa7FBoKk02/He8bnnZsv9FvEb8IviTzhmHFt9iU5rTqXfM8OWc7OaYkKKUO83naGiJD4rTtOnV6/syE83cmOYy6jVhAWeYCcNHUyHfhad3h1i66U6WjEbjuM/8h9iLns1XuS0juCNSCrJLLyRz+GP5MIVsz01bqM1yGYbbzKkq2R0p/KTFFiCOdFGrxZpT/TNLROas5F0y6uuBY94STCk00ycHSQ1DF/dgQo3FIvEnNmvebLx3Ox4AMLjHVump5aWIeCJ9eNSFRbnsTDvhzULHprecxH0ifi6xu9WEf1goIkINAUWrOVQ7CkhWu5VShLll robotarmy@Ryans-MBP.lan"
    - name: jamesbelchamber
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdZabv0pxFgpC5Q1N6FXpwTLuvI4BbFAi46lTWPxL7wkoGtYaA2sCbVkqK0C6/7Q31Rk1Xdbv+pxhXBDjPcmsVBxoKZgyzDrXVYXNEhKcz8WWqAVTjaeLueb5vyyWr/DLezj8TNw2XFzmgGHazJQDyVT29kcmcNRrboI9poHAkiLuSK/AX8rDLoAAI638rysK60egqg6wrV/JWsT4c6otSb8fUseDxS/aLaAYnd9VekhaG8tzjtXN52gCAHdfaXygJHtSvor17Q6fwH/WSMcPhR+6g6Dxxbq4v/qOooKoy+GbZKlXYXRxPBCXFrPhqRy8QZHh2Hrfz5L88fRorBN+j james@pyre"
    - name: jeremy
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAzQeT7p3W1HGMZETrOuQim8t+afBfIq4JlRPWU4OZFdmooXxoNVZw32KwkGXoD5eMg86mgo0WjjI3YmZMXzhquIuaq+7hKh1NEA69lraicwEFQQeESXLJ8BrxuuNp7lcFSKx8Pce/ywdc9efP52jVv4uJFOonS35n1Wig/Ohzk4fp+nZzxpTQiFd2BI1qE7X4IKmAp00sJv8ZL3b0317i/Q8XZoxew3HtMBkI9plWZDHIzUB5bzaqZhuIHRW9hnU8W9Ne+b4D2UHxICpSNHC9rKpmG4D6MXkd8rBfoB6QZ87RgO9/EbbrytuX4b0tYZwiC5Wm6YLVetBn7jY9Wnw+5Q== jeremy@pogotron"
